phrases = {
    "settings_text": "⚙️ Here you can manage your personal bot settings",
    "start_message": "<b>Welcome to Cleover Bot!</b> ☘️\n\nWe're thrilled to have you on board! <b>Our mission is to maximize your earnings in Crypto</b>.\n\n<b>Here's what you can expect</b>:\n<b>•</b> Daily Insights\n<b>•</b> Unique Calls\n<b>•</b> Tools & Resources\n<b>•</b> Real-time Alerts\n\nLet's embark on this exciting journey together and unlock your potential in the crypto!  🚀\n\n<b>We're waiting for you!</b> 🧠",
    "feedback_text": "📥 <b>Feedback</b>\n\nYou can write here your opinion about Cleover and also suggest innovations. Each message will be reviewed by the team. Maybe you will make Clevoer Bot even better 🧠☘️",
    "activities_text": "💡 <b>Pick the areas of crypto that interest you.</b>\n\nYou will receive a messages of activities related to these areas",
    "subscriptions_text": "Please select a subscription option:",
    "expiration_sub_date": "Your subscription will end:",
    "renew_subscription": "\n\nHere you can renew your bot subscription:",
    "support_text": "❓ <b>Support</b>\n\nIf you have any problems with the bot you can write to our manager: @l1qrty",
    "instruction_text": "📜 <b>Instruction</b>\n\nOur team has written <a href='https://telegra.ph/CLEOVER-BOT--INSTRUCTION-06-11-2'>a detailed guide for using Cleover Bot</a>. If you are experiencing any difficulties we advise you to read it.",
    "notification_text": "🔔 <b>Notification</b>\n\nTime of the first activity reminder",
    "bank_text": "💸 <b>Your bank</b>\n\nPick your bank for better news selection",
    "wait_payment_text": "⌛ Please wait, an invoice is being created...",
    "error_create_payment": "🤷 Failed to create an invoice, please try again!",
    "subscription_date": "🎉 <b>Congratulations!</b> Your subscription is valid until ",
    "choise_project_category": "📚 Select the category of projects that interest you:",
    "choise_project": "💻 Select the project that interests you:",
    "choise_project_news": "👀 See interesting news about this project 👇",
    "sub_was_canceled": "‼ Attention! Your subscription has expired. Please extend it 👇",
    "user_post_feedback": "<b>Thank you for your feedback! 💌</b>\n\nOur team will definitely consider your proposal and will do everything to make Cleover better! 🧠☘️",
    "admin_show_feedback": "🆕 <b>Обратная связь!</b>\n\n",
    "activities_list": "💡 <b>Select the activity you want to learn about.</b>",
    "referral_system": "Our <b>referral system allows each user to refer friends and receive bonuses</b> for each new subscriber who signs up through your link! 💸🗣\n\n",
    "new_referral_notification": "🎉 Congratulations! You have <b>a new referral</b>!",
    "withdrawal_in_process": "🔄 Your withdrawal request <b>is being processed</b>, please wait!\n\n<b>P.S.</b> If you have any questions, write to support.",
    "insufficient_funds": "❗ You don't have enough funds on your balance sheet! Minimum withdrawal amount - <b>100$</b>\n\n<b>P.S.</b> If you have any questions, write to support.",
    "wallet_enter": "💸 Enter your <b>USDT BEP-20</b> wallet.\n\n‼ Make sure that the <b>entered wallet is correct</b>! Administration <b>is not responsible</b> for sending funds to an incorrect wallet! ‼",
}
